[package]
name = "rover-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
jsonwebtoken = "9.3"
serde = { version = "1.0", features = ["derive"] }
mlua = { version = "0.11.5", features = ["anyhow", "vendored", "luajit52", "serialize"] }
serde_json = "1.0"
