[package]
name = "rover_bundler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rover-parser = { path = "../rover-parser" }
tree-sitter = "0.26.3"
tree-sitter-lua = "0.2.0"

[dev-dependencies]

[lib]
name = "rover_bundler"
crate-type = ["lib"]
