[package]
name = "rover_server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.7"
mlua = "0.11.5"
tokio = {version="1.48.0", features=["full"]}


[lib]
crate-type = ["cdylib", "lib"]
bench = false
