[package]
name = "rover-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.146"
tree-sitter = "0.26.3"
tree-sitter-lua = "0.2.0"
stylua_lib = { package = "stylua", version = "2.3", default-features = false, features = ["lua54"] }
